### ISSUE TITLE
Stop = not working

### ISSUE THREAD

**Issue by finnie2006** [bandi13/gui-docker#1]
When i stop the container and then start it again using portainer or using docker start i get the following error
![afbeelding](https://user-images.githubusercontent.com/57916807/134817638-5f80b627-6241-483a-af37-ece628b5a773.png)
Translated: connection with the server failed, also have the same problem with ur obs docker image

**Comment by bandi13** [comment]
That's true. I didn't design these containers to be stopped and started. That's because with a XWindow environment, you can start up a lot of other programs that would not get resumed either.

As a workaround, you could probably do something like run the 'container_startup.sh' script upon restarting the container. That should start everything back up that is necessary for the VNC stuff to work.

**Comment by finnie2006** [comment]
hmm

**Comment by oldunclez** [comment]
>  do something like run the 'container_startup.sh' script upon restarting the container.

@bandi13  could you plz explain it a bit more ?

Accidentally , I find a workaroud :

1.  restart to container :  docker stop xxx , docker start xxx
2.  enter the container :    docker exec -it xxx /bin/bash 
3.  run this cmd :  
`/usr/bin/Xtigervnc :0 -desktop 0705d1500b1d:0 -auth /root/.Xauthority -geometry 1900x1200 -depth 24 -rfbwait 30000 -rfbauth /root/.vnc/passwd -rfbport 5900 -pn -SecurityTypes VncAuth,TLSVnc -nolisten &`
4. find the pid of the above cmd and then kill it  :  ps aux |grep /usr/bin/Xtigervnc  ; kill XXX
5. run this cmd : 
   `vncserver :0 -localhost no -nolisten -rfbauth $HOME/.vnc/passwd -xstartup /opt/x11vnc_entrypoint.sh`
6. leave  the container

I donot understand it completely , but it seems that it works.
